use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let bins_dir = manifest_dir.join("../bins");
    println!("cargo::rerun-if-changed={}", bins_dir.display());

    let mut bins: Vec<_> = fs::read_dir(&bins_dir)
        .unwrap()
        .map(|entry| entry.unwrap())
        .filter(|entry| entry.file_type().unwrap().is_file())
        .collect();
    bins.sort_by_key(|entry| entry.file_name());

    let mut generated = String::from("// This file is generated by elf_tests/build.rs.\n");
    for bin in bins {
        let file_name = bin.file_name();
        let file_name = file_name.to_str().unwrap();
        generated.push_str(&format!(
            "pub static {file_name}: &'static [u8] = \
             include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../bins/{}\"));\n",
            file_name
        ));
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out_dir.join("bins.rs"), generated).expect("failed to write generated exports");
}
